Fix warning using ERR_FAIL_INDEX on unsigned int
This method starting being used in 5f066ccbb35581d252cf00c7156615d86faed02f,
which now triggers this warning from GCC 10:
```
./core/error_macros.h:151:25: error: comparison of unsigned expression in '< 0' is always false [-Werror=type-limits]
```